---
default_stages: [commit, push]
fail_fast: true

repos:

  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: system
        args: [-c, .config/yamllint.yaml]
        files: '\.(yaml|yml)$'


  # TODO: Fix ansible-lint
  # - repo: https://github.com/ansible-community/ansible-lint.git
  #   rev: v6.21.1
  #   hooks:
  #     - id: ansible-lint
  #       files: \.(yaml|yml)$
