---


- name: Change root password
  ansible.builtin.user:
    name: root
    password: "{{ root_password | password_hash }}"
    state: present
    update_password: on_create

- name: Include instalation of core packages
  ansible.builtin.include_tasks: install_core_packages.yaml

# TODO: Include nvidia driver installation if it has nvidia gpu

- name: Include window manager tasks
  ansible.builtin.include_tasks: install_window_manager_packages.yaml

- name: Include transmission
  ansible.builtin.include_tasks: install_transmission.yaml

- name: Include installation of root certificate
  ansible.builtin.include_tasks: install_root_certificate.yaml

- name: Configure user
  ansible.builtin.include_tasks: user_configuration.yaml
  loop: "{{ users }}"
  loop_control:
    loop_var: user
