---

- name: Update cache
  community.general.pacman:
    update_cache: true

- name: Upgrade linux kernel
  community.general.pacman:
    state: latest
    name:
      - linux-headers
  notify: Reboot

# TODO: Add paru update to update role for arch linux after normal update
- name: Upgrade pacman packages
  community.general.pacman:
    update_cache: true
    upgrade: true
