---


- name: Deploy Portainer agent container
  community.docker.docker_container:
    name: portainer_agent
    image: "{{ portainer_agent_image }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
    ports:
      - "9001:9001"
    restart_policy: "unless-stopped"
    detach: true
  notify: Restart docker


  # TODO: Limit this to portainer instance ip address ( src )
- name: Open portainer agent port
  community.general.ufw:
    rule: allow
    port: 9001
    comment: "ALLOW Portainer Agent Endpoint"
  notify: Reload ufw


- name: Remove old docker image versions
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false


- name: Flush handlers
  ansible.builtin.meta: flush_handlers
