---
- name: Restart acpid
  service:
    name: acpid
    state: restarted


- name: Restart network manager
  service:
    name: NetworkManager
    state: restarted


- name: Restart cups
  service:
    name: cups
    state: restarted


- name: Restart bluetooth
  service:
    name: bluetooth
    state: restarted


- name: Restart libvirtd
  service:
    name: libvirtd
    state: restarted


- name: Restart lightdm
  service:
    name: lightdm
    state: restarted


- name: Restart zramd
  service:
    name: zramd
    state: restarted


- name: Restart snapd
  service:
    name: snapd
    state: restarted


- name: Restart avahi
  service:
    name: avahi-daemon
    state: restarted


- name: Reload transmission
  service:
    name: transmission
    state: reloaded

- name: Update trusted certificates
  ansible.builtin.command:
    cmd: 'update-ca-trust'


# TODO: Uncomment fail condition when issue with exit codes is fixed
- name: Build initramd
  ansible.builtin.command: /usr/bin/mkinitcpio -p linux
  changed_when: true
  # failed_when: mkinitcpio_result.rc != 0
  failed_when: false


# TODO: Add to wait for reconnection
- name: Reboot the system
  ansible.builtin.reboot:
