---

- name: Ensure server is configured
  hosts: portainer
  become: true
  roles:
    - role: core
    - role: update
    - role: sshd
    - role: vm_guest
    - role: firewall
    - role: docker
    - role: portainer
